
image:
  file: .gitpod.dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: >
      chmod +x app.bash &&
      python3 -m venv venv &&
      . venv/bin/activate &&
      ./app.bash install
    command: ./app.bash start

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - mblode.pretty-formatter